runtime: java8
env: standard

handlers:
- url: /.*
  script: this field is required, but ignored

beta_settings:
  cloud_sql_instances: automatic-curve-358618:us-central1:test-server

runtime_config:
  jdk: openjdk8
  server: jetty9

manual_scaling:
  instances: 1
resources:
  cpu: 0.50
  memory_gb: 1
  disk_size_gb: 0.25